# Great example travis.yml for many compiler versions https://github.com/taocpp/PEGTL/blob/master/.travis.yml

language: cpp

jobs:
  include:
    - os: linux
      compiler: cmake
      addons:
        apt:
          packages:
            - doxygen
            - lcov
      before_script:
        - make --version
        - doxygen -v
        - mkdir build
        - cd build
        # Option -D CODE_COVERAGE=ON generates target anamark-tuning-library_coverage
        - cmake -D CMAKE_BUILD_TYPE=Release -D CODE_COVERAGE=ON ..
        - ls
        - make
        # Documentation coverage (pass with even 0 documentation coverage)
        - python ../cmake/doxy-coverage.py ../build/docs/xml/ --badgelocation ../build/docs/html/ --threshold 0
        # Generate coverage reports
        - export ANAMARK_TEST_DATA_DIRECTORY=../tests/data/
        - make anamark-tuning-library_coverage
        # Create lcov report
        - lcov --capture --directory . --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' '*/catch2.hpp' --output-file coverage.info # filter system-files
        - lcov --list coverage.info # debug info
        # Uploading report to CodeCov
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
        # Unset test data directory back to default
        - unset ANAMARK_TEST_DATA_DIRECTORY
        - cd ..
      deploy:
        provider: pages
        local_dir: build/docs/html/
        token: $GH_REPO_TOKEN
        keep_history: true
        strategy: git
        # Opt into deployment tooling (dpl) version 2
        edge: true
        on:
          branch: develop
    - os: osx
      compiler: cmake
      before_script:
        - cmake -B build
        - cmake --build build --config Release
    - os: windows
      compiler: cmake
      # before_install:
      #   - choco install make
      before_script:
        - cmake -B build
        - cmake --build build --config Release

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\build\\Release\\anamark-tuning-test.exe; else ./build/anamark-tuning-test; fi
